import type { SolarAppliance } from "@/types/solar-finder";

export const appliances: SolarAppliance[] = [
  {
    id: "led-lights",
    name: "LED Lights",
    category: "lighting",
    estimatedWatts: 10,
    surgeMultiplier: 1,
    defaultQuantity: 4,
    allowQuantity: true,
    icon: "Lightbulb",
  },
  {
    id: "television",
    name: "Television",
    category: "entertainment",
    estimatedWatts: 120,
    surgeMultiplier: 1.2,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Tv",
  },
  {
    id: "wifi-router",
    name: "WiFi Router",
    category: "communication",
    estimatedWatts: 15,
    surgeMultiplier: 1,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Wifi",
  },
  {
    id: "phone-chargers",
    name: "Phone Chargers",
    category: "communication",
    estimatedWatts: 10,
    surgeMultiplier: 1,
    defaultQuantity: 2,
    allowQuantity: true,
    icon: "Smartphone",
  },
  {
    id: "laptop",
    name: "Laptop",
    category: "work",
    estimatedWatts: 65,
    surgeMultiplier: 1,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Laptop",
  },
  {
    id: "desktop-computer",
    name: "Desktop Computer",
    category: "work",
    estimatedWatts: 250,
    surgeMultiplier: 1.5,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Monitor",
  },
  {
    id: "refrigerator",
    name: "Refrigerator",
    category: "cooling",
    estimatedWatts: 150,
    surgeMultiplier: 3,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Refrigerator",
  },
  {
    id: "deep-freezer",
    name: "Deep Freezer",
    category: "cooling",
    estimatedWatts: 200,
    surgeMultiplier: 3,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Snowflake",
  },
  {
    id: "decoder",
    name: "Decoder",
    category: "entertainment",
    estimatedWatts: 25,
    surgeMultiplier: 1,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Radio",
  },
  {
    id: "fans",
    name: "Fans",
    category: "cooling",
    estimatedWatts: 75,
    surgeMultiplier: 2,
    defaultQuantity: 2,
    allowQuantity: true,
    icon: "Wind",
  },
  {
    id: "microwave",
    name: "Microwave",
    category: "kitchen",
    estimatedWatts: 1000,
    surgeMultiplier: 1,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Microwave",
  },
  {
    id: "electric-kettle",
    name: "Electric Kettle",
    category: "kitchen",
    estimatedWatts: 1800,
    surgeMultiplier: 1,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "CookingPot",
  },
  {
    id: "washing-machine",
    name: "Washing Machine",
    category: "kitchen",
    estimatedWatts: 500,
    surgeMultiplier: 2,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "WashingMachine",
  },
  {
    id: "borehole-pump",
    name: "Borehole Pump",
    category: "water",
    estimatedWatts: 1500,
    surgeMultiplier: 3,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Water",
  },
  {
    id: "water-pump",
    name: "Water Pump",
    category: "water",
    estimatedWatts: 750,
    surgeMultiplier: 3,
    defaultQuantity: 1,
    allowQuantity: true,
    icon: "Droplets",
  },
  {
    id: "cctv",
    name: "Security System / CCTV",
    category: "security",
    estimatedWatts: 60,
    surgeMultiplier: 1,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Camera",
  },
  {
    id: "office-equipment",
    name: "Office Equipment",
    category: "business",
    estimatedWatts: 400,
    surgeMultiplier: 1.5,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Printer",
  },
  {
    id: "shop-equipment",
    name: "Shop Equipment",
    category: "business",
    estimatedWatts: 800,
    surgeMultiplier: 2,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Store",
  },
  {
    id: "other",
    name: "Other",
    category: "other",
    estimatedWatts: 200,
    surgeMultiplier: 1.5,
    defaultQuantity: 1,
    allowQuantity: false,
    icon: "Plug",
  },
];

export function getApplianceById(id: string): SolarAppliance | undefined {
  return appliances.find((a) => a.id === id);
}

export function getAppliancesByCategory(category: string): SolarAppliance[] {
  return appliances.filter((a) => a.category === category);
}
